language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

services:
  - memcached

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

before_install:
  - phpenv config-add tests/travis.ini
  - nvm install node

install:
  - composer install --no-interaction
  - bash vendor/miaoxing/plugin/build/install-travis.sh

script:
  - bash vendor/miaoxing/plugin/build/build-travis.sh --coverage 1

after_success:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - travis_retry php coveralls.phar -v --exclude-no-stmt
